version: '3'

services:
  api-db:
    image: redis:5.0.3-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - api-db-data:/data

  api:
    build: api/
    image: casperpijnenburg/docker-test-api
    volumes:
      - ./api/src:/api

  website:
    build: website/
    image: casperpijnenburg/docker-test-website
    volumes:
      - ./website/:/app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  proxy:
    build: proxy/
    image: casperpijnenburg/docker-test-proxy
    ports:
      - 8080:80

volumes:
  api-db-data: